spring:
  application:
    name: hexagonal
  sql:
    init:
      mode: always
      data-locations: classpath:data-test.sql
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
